name: Tuesday Matching Algorithm
on:
  schedule:
    - cron: '0 12 * * 2'  # Every Tuesday at 12:00 UTC (9:00 AM Paraguay)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-matching:
    runs-on: ubuntu-latest
    steps:
      - name: Call MesaNoche Matching Algorithm
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            https://dvsnaadrevyygokqsgey.supabase.co/functions/v1/tuesday-matching-algorithm
